### PR TITLE
try using a closure for caching

### PR DESCRIPTION
**Pull request by maelle**
cf #1 

Not sure I'm very helpful here  @gaborcsardi ... Am very glad to learn if you can review this PR though 😀

### CODE REVIEW

**Comment by maelle** [comment]
Clearly I'm not doing it right. 🤔

**Comment by maelle** [comment]
I should have read the docs... "assignInNamespace should not be used in final code, and will in future throw an error if called from a package. Already certain uses are disallowed."

**Comment by maelle** [comment]
For some reason now it passes on oldrel but not elsewhere.

**Comment by maelle** [comment]
I think the tests are run on all R versions but they only fail on oldrel 🤔 

```r
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
  ── 1. Error: Github username works (@test-gh-username.R#22)  ───────────────────
  no binding for "get_gh_username"
  1: expect_equal(gh_username(), "gaborcsardi") at testthat/test-gh-username.R:22
  2: quasi_label(enquo(object), label)
  3: eval_bare(get_expr(quo), get_env(quo))
  4: gh_username()
  5: assignInMyNamespace("get_gh_username", .get_gh_username())
  6: bindingIsLocked(x, ns)
```

**Comment by maelle** [comment]
At the commit before that tests only passed on oldrel... Clearly I'm doing something wrong! 🔍

**Comment by maelle** [comment]
I'm starting to think I need to re-write the test actually, just to make sure it's not the mocking that prevents the assignInMyNamespace (maybe the whole thing is smelly but it works for me so I want tests to pass at least :joy:)

**Comment by gaborcsardi** [comment]
Thanks! I fixed this with a somewhat simpler solution: 860cbf99ab89e366d79ac290076025052325c7ce

**Comment by maelle** [comment]
Awesome! Maybe write "cache (...) in the active session"?

**Pull request closed without merging**
